# Generated by Django 4.1.5 on 2023-05-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('casa', models.BooleanField()),
                ('dpto', models.BooleanField()),
                ('piso', models.IntegerField(verbose_name=10)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreR', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut del usuario')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('fono', models.IntegerField()),
                ('clave', models.CharField(max_length=15)),
                ('respuesta', models.CharField(max_length=20)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.pregunta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fVenta', models.DateField(verbose_name='Fecha de la venta')),
                ('fEntrega', models.DateField(verbose_name='Fecha de la entrega')),
                ('estadoP', models.BooleanField(verbose_name='estado del producto')),
                ('total', models.IntegerField()),
                ('carrito', models.BooleanField()),
                ('status', models.BooleanField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('descipcion', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='VFA_PetShop')),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.venta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VFA_Pet.region'),
        ),
    ]
