# Generated by Django 4.1.5 on 2023-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VFA_Pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='casa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='dpto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='carrito',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estadoP',
            field=models.IntegerField(verbose_name='estado del producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='status',
            field=models.IntegerField(),
        ),
    ]
