# Generated by Django 4.1.5 on 2023-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VFA_Pet', '0002_alter_direccion_casa_alter_direccion_dpto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=40),
        ),
    ]
