# Generated by Django 4.2.1 on 2023-06-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VFA_Pet', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descipcion',
            field=models.CharField(max_length=100),
        ),
    ]
