# Generated by Django 4.2.1 on 2023-06-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VFA_Pet', '0004_alter_producto_descipcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='respuesta',
            field=models.CharField(max_length=50),
        ),
    ]
